In [2]:
import tensorflow as tf

ze = tf.zeros([2,2])

sess = tf.Session()
sess.run(ze)

array([[ 0.,  0.],
       [ 0.,  0.]], dtype=float32)

In [3]:
on = tf.ones([6])
sess.run(on)

array([ 1.,  1.,  1.,  1.,  1.,  1.], dtype=float32)

In [4]:
uni = tf.random_uniform([3,3,3],minval=0,maxval=10)
sess.run(uni)

array([[[ 9.48161983,  1.10813975,  1.5646255 ],
        [ 3.32675576,  3.18508744,  1.49714112],
        [ 4.87299442,  6.19046593,  4.33700466]],

       [[ 3.16252351,  4.38668966,  2.57008433],
        [ 0.62650681,  7.40463829,  1.13970518],
        [ 5.9338975 ,  9.11876106,  7.56358528]],

       [[ 3.22684169,  2.13731885,  6.82518721],
        [ 2.84255266,  1.10862613,  7.42506123],
        [ 8.16436672,  3.28405857,  7.99957657]]], dtype=float32)

In [5]:
unif = tf.random_uniform([3,3,3],mean=0.0,stddev=1.0)
sess.run(unif)

array([[[ 0.37526953,  0.88399625,  0.05687559],
        [ 0.0932914 ,  0.49686861,  0.78296661],
        [ 0.38553798,  0.22923589,  0.45879662]],

       [[ 0.6504339 ,  0.25795364,  0.13353503],
        [ 0.97072315,  0.74749255,  0.50466788],
        [ 0.41360915,  0.84266913,  0.92527986]],

       [[ 0.31087708,  0.13986635,  0.44553888],
        [ 0.8271172 ,  0.17037308,  0.34316969],
        [ 0.25227702,  0.90775943,  0.94207406]]], dtype=float32)

In [7]:
unic = tf.truncated_normal([2,3],mean=5.0,stddev=1.0)
sess.run(unic)

array([[ 6.10342884,  4.33925915,  4.76290751],
       [ 4.53868818,  5.69373035,  6.76475811]], dtype=float32)

In [11]:
var = tf.Variable(1)

var2 = var.assign(var*3)
# init = tf.initialize_all_variables()

init = tf.global_variables_initializer()

sess.run(init)

sess.run(var2)

3

In [20]:
# -*- coding: utf8 -*-

import tensorflow as tf

class ModelV():

    def __init__(self):

        self.v1 = tf.Variable(66, name="v1")
        self.v2 = tf.Variable(77, name="v2")
        self.save_path = "model/tf_base_2_v.ckpt"
        self.init = tf.global_variables_initializer()

        self.sess = tf.Session()

    def train(self):
        saver = tf.train.Saver([self.v1, self.v2])
        self.sess.run(self.init)
        print 'v2', self.v2.eval(self.sess)

        saver.save(self.sess, self.save_path)
        print "ModelV saved."

    def predict(self):
        saver = tf.train.Saver([self.v1, self.v2])
        all_vars = tf.trainable_variables()
        for v in all_vars:
            print v.name

        v_vars = [v for v in all_vars if v.name == 'v1:0' or v.name == 'v2:0']
        print "ModelV restored."
        saver.restore(self.sess, self.save_path)
        for v in v_vars:
            print v.name,v.eval(self.sess)  
        print 'v2', self.v2.eval(self.sess)
        print '------------------------------------------------------------------'

class ModelP():

    def __init__(self):

        self.p1 = tf.Variable(88, name="p1")
        self.p2 = tf.Variable(99, name="p2")
        self.save_path = "model/tf_base_2_p.ckpt"
        self.init = tf.global_variables_initializer()
        self.sess = tf.Session()

    def train(self):
        saver = tf.train.Saver([self.p1, self.p2])
        self.sess.run(self.init)
        print 'p2', self.p2.eval(self.sess)

        saver.save(self.sess, self.save_path)
        print "ModelP saved."

    def predict(self):
        saver = tf.train.Saver([self.p1, self.p2])
        all_vars = tf.trainable_variables()
        p_vars = [v for v in all_vars if v.name == 'p1:0' or v.name == 'p2:0']
        for v in all_vars:
            print v.name
            #print v.name,v.eval(self.sess)
        saver.restore(self.sess, self.save_path)
        print "ModelP restored."
        for p in p_vars:
            print p.name,p.eval(self.sess)
        print 'p2', self.p2.eval(self.sess)
        print '----------------------------------------------------------'


if __name__ == '__main__':
    v = ModelV()
    p = ModelP()
    
    v.predict()
    #v.train()
    p.predict() 
    #p.train()

Variable:0
Variable_1:0
Variable_2:0
Variable_3:0
v1:0
v2:0
p1:0
p2:0
v1_1:0
v2_1:0
p1_1:0
p2_1:0
v1_2:0
v2_2:0
p1_2:0
p2_2:0
v1_3:0
v2_3:0
p1_3:0
p2_3:0
v1_4:0
v2_4:0
p1_4:0
p2_4:0
v1_5:0
v2_5:0
p1_5:0
p2_5:0
ModelV restored.


NotFoundError: Key v1_5 not found in checkpoint
	 [[Node: save_8/RestoreV2 = RestoreV2[dtypes=[DT_INT32], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_8/Const_0, save_8/RestoreV2/tensor_names, save_8/RestoreV2/shape_and_slices)]]

Caused by op u'save_8/RestoreV2', defined at:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/chris/.tensor/lib/python2.7/site-packages/ipykernel/__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "/Users/chris/.tensor/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/Users/chris/.tensor/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 474, in start
    ioloop.IOLoop.instance().start()
  File "/Users/chris/.tensor/lib/python2.7/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/Users/chris/.tensor/lib/python2.7/site-packages/tornado/ioloop.py", line 887, in start
    handler_func(fd_obj, events)
  File "/Users/chris/.tensor/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/chris/.tensor/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/Users/chris/.tensor/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/Users/chris/.tensor/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/Users/chris/.tensor/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/chris/.tensor/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 276, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/Users/chris/.tensor/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "/Users/chris/.tensor/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 390, in execute_request
    user_expressions, allow_stdin)
  File "/Users/chris/.tensor/lib/python2.7/site-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/Users/chris/.tensor/lib/python2.7/site-packages/ipykernel/zmqshell.py", line 501, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/Users/chris/.tensor/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2717, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/Users/chris/.tensor/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2821, in run_ast_nodes
    if self.run_code(code, result):
  File "/Users/chris/.tensor/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-20-e2156e47c8f6>", line 75, in <module>
    v.predict()
  File "<ipython-input-20-e2156e47c8f6>", line 25, in predict
    saver = tf.train.Saver([self.v1, self.v2])
  File "/Users/chris/.tensor/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1000, in __init__
    self.build()
  File "/Users/chris/.tensor/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1030, in build
    restore_sequentially=self._restore_sequentially)
  File "/Users/chris/.tensor/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 624, in build
    restore_sequentially, reshape)
  File "/Users/chris/.tensor/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 361, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/Users/chris/.tensor/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 200, in restore_op
    [spec.tensor.dtype])[0])
  File "/Users/chris/.tensor/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 441, in restore_v2
    dtypes=dtypes, name=name)
  File "/Users/chris/.tensor/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 759, in apply_op
    op_def=op_def)
  File "/Users/chris/.tensor/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2240, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/Users/chris/.tensor/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1128, in __init__
    self._traceback = _extract_stack()

NotFoundError (see above for traceback): Key v1_5 not found in checkpoint
	 [[Node: save_8/RestoreV2 = RestoreV2[dtypes=[DT_INT32], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_8/Const_0, save_8/RestoreV2/tensor_names, save_8/RestoreV2/shape_and_slices)]]
